"""user first and last name

Revision ID: 98fe040627d7
Revises: 2f41c421e0c7
Create Date: 2024-04-21 15:13:45.094508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fe040627d7'
down_revision: Union[str, None] = '2f41c421e0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user_user', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_user', 'last_name')
    op.drop_column('user_user', 'first_name')
    # ### end Alembic commands ###
